# -*- coding: utf-8 -*-
"""default loan prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9BHaoPxp1XNjbCVU8buB-5WoouyQK9M
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("numpy", np.__version__)
print("pandas", pd.__version__)
print("seaborn", sns.__version__)
print("sklearn",sklearn.__version__)

# load data
train = pd.read_csv("train_u6lujuX_CVtuZ9i.csv")
test  = pd.read_csv("test_Y3wMUE5_7gLdaTN.csv")

# basic checks
print("Train shape:", train.shape)
print("Test shape:", test.shape)

train.head()

train.isnull().sum()

train['Loan_Status'].value_counts()

train['Loan_Status'].value_counts(normalize=True)

# Categorical columns
train['Gender'].fillna(train['Gender'].mode()[0], inplace=True)
train['Married'].fillna(train['Married'].mode()[0], inplace=True)
train['Dependents'] = train['Dependents'].replace('3+', 3).astype(float)
#train['Dependents'].fillna(train['Dependents'].mode()[0], inplace=True)
train['Self_Employed'].fillna(train['Self_Employed'].mode()[0], inplace=True)

# Numerical columns
train['LoanAmount'].fillna(train['LoanAmount'].median(), inplace=True)
train['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].mode()[0], inplace=True)
train['Credit_History'].fillna(train['Credit_History'].mode()[0], inplace=True)

# Encode categorical variables
train['Gender'] = train['Gender'].map({'Male': 1, 'Female': 0})
train['Married'] = train['Married'].map({'Yes': 1, 'No': 0})
train['Education'] = train['Education'].map({'Graduate': 1, 'Not Graduate': 0})
train['Self_Employed'] = train['Self_Employed'].map({'Yes': 1, 'No': 0})
train['Loan_Status'] = train['Loan_Status'].map({'Y': 1, 'N': 0})

# Total Income
train['Total_Income'] = train['ApplicantIncome'] + train['CoapplicantIncome']

# Log transform skewed features
train['LoanAmount_log'] = np.log(train['LoanAmount'])
train['Total_Income_log'] = np.log(train['Total_Income'])

plt.figure(figsize=(8,5))
sns.histplot(train['LoanAmount'], bins=30, kde=True)
plt.title('Distribution of Loan Amount')
plt.show()

sns.countplot(x='Loan_Status', data=train)
plt.title('Loan Approval Status')
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(x='Credit_History', hue='Loan_Status', data=train)
plt.title('Loan Status vs Credit History')
plt.show()

sns.countplot(x='Education', hue='Loan_Status', data=train)
plt.title('Loan Status vs Education')
plt.show()

sns.boxplot(x='Loan_Status', y='ApplicantIncome', data=train)
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(train.select_dtypes(include=[np.number]).corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Features (exclude Loan_ID and target)
X = train[['Gender', 'Married', 'Education', 'Self_Employed', 'Dependents',
           'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
           'Loan_Amount_Term', 'Credit_History', 'Total_Income',
           'LoanAmount_log', 'Total_Income_log']]

# Target
y = train['Loan_Status']

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,      # Number of trees
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred))

import joblib
joblib.dump(rf_model, "loan_model.pkl")

print("joblib", joblib.__version__)